# Generated by Django 5.1.3 on 2025-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_choice',
            field=models.CharField(blank=True, choices=[('dev', 'Dev'), ('ninja', 'Ninja'), ('robot', 'Robot'), ('wizard', 'Wizard'), ('astro', 'Astronauta'), ('motorist', 'Motorista')], default='', max_length=16),
        ),
    ]
