# Generated by Django 5.1.3 on 2025-09-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_choice',
            field=models.CharField(blank=True, choices=[('dev', 'Dev'), ('ninja', 'Ninja'), ('robot', 'Robot'), ('wizard', 'Wizard'), ('astro', 'Astronauta')], default='', max_length=16),
        ),
    ]
