# Generated by Django 5.1.3 on 2025-09-17 23:49

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=projects.models.image_upload_path, validators=[projects.models.validate_image_ext, projects.models.validate_image_size_5mb])),
                ('preview', models.FileField(blank=True, help_text='Sube un MP4 ligero (recomendado) o una imagen (WEBP/JPG/PNG).', max_length=255, null=True, upload_to=projects.models.preview_upload_path, validators=[projects.models.validate_preview_ext, projects.models.validate_preview_size_20mb])),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx')],
            },
        ),
    ]
