# Generated by Django 5.1.3 on 2025-07-25 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('preview', models.FileField(blank=True, help_text='Sube un archivo .mp4 o .gif para la previsualización.', null=True, upload_to='projects/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'gif'])])),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
