# Generated by Django 5.1.3 on 2025-07-26 02:14

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.FileField(blank=True, help_text='Sube un .mp4 o .gif para la previsualización.', max_length=255, null=True, upload_to=projects.models.preview_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'gif'])]),
        ),
    ]
