# Usa el provider oficial de Python de Nixpacks
[providers.python]
version = "3.12"

# Si necesitas ffmpeg, añádelo como nixPkg adicional
[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]
