# Generated by Django 5.1.3 on 2025-09-26 23:31

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.image_upload_path, validators=[services.models.validate_image_ext, services.models.validate_image_size_5mb])),
                ('preview', models.FileField(blank=True, help_text='Sube un MP4 ligero (recomendado) o una imagen (WEBP/JPG/PNG).', max_length=255, null=True, upload_to=services.models.preview_upload_path, validators=[services.models.validate_preview_ext, services.models.validate_preview_size_20mb])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'title'],
                'indexes': [models.Index(fields=['-is_active', 'title'], name='services_se_is_acti_3abeb7_idx'), models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'), models.Index(fields=['price'], name='services_se_price_4a7bf9_idx'), models.Index(fields=['-created_at'], name='services_se_created_d8afb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text="Opcional: nombre de icono (p.ej. 'check', 'bolt', etc.).", max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
