# Generated by Django 5.1.3 on 2025-07-25 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('preview', models.FileField(blank=True, help_text='Carga un .mp4 o un .gif para la vista previa.', null=True, upload_to='service_previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'gif'])])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
