# Generated by Django 5.1.3 on 2025-07-26 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.FileField(blank=True, help_text='Carga un .mp4 o un .gif para la vista previa.', max_length=500, null=True, upload_to='service_previews/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'gif'])]),
        ),
    ]
