# Generated by Django 5.1.3 on 2025-07-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=60, null=True, unique=True),
        ),
    ]
